### PR TITLE
The Current Volume Sensor should return the master volume level

### LINKED ISSUE #86: Current Volume Sensor does not return the correct volume
If i set the master volume of my speakers to max, the sensor should return 100% and if I mute the sound it should return 0%. 

It seems the sensor returns the calculated peak level of the sound not the speaker volume. The value of the sensor changes if i play music also I don't change the windows sound value.

image

### PR DESCRIPTION
**Pull request by sgebhardt**
The sensor now returns the master volume level of the current default device.
This fixes #86

### CODE REVIEW

**Comment by sleevezipper** [comment]
Hey thanks for your PR! I think both implementations provide value and I'd prefer not to break the current sensor for users already using it. Would you mind if I turn your implementation in a separate sensor? Say, a SetVolumeSensor?

**Comment by sgebhardt** [comment]
Hi, i think you are right. This should not break the compatibility. I will update this pull request.

**Comment by sgebhardt** [comment]
I think it is cleaner if i create a new PR with the new sensor.

**Comment by sleevezipper** [comment]
This has been implemented further by @SecretiveShell in #123 so I'll close this one.

**Comment by sgebhardt** [comment]
That is great. Thanks @SecretiveShell.

**Comment by SecretiveShell** [comment]
You did all the hard work @sgebhardt !

**Pull request closed without merging**
