### PR TITLE
Create Command for Hibernate

### PR DESCRIPTION
**Pull request by department-g33k**
Hi!  I like what you're doing here!  I'm used to Hibernating my computer, and that seems like the only thing your project doesn't do that I was looking for.  I'm hoping I can be helpful, so I created a command to issue "shutdown /h"

I don't have the toolchain to test this, or add an option to the UI.  If this isn't a direction you'd like to go, please disregard.

I hope I'm not coming across rude/presumptuous, I'm new to contributing and I'm hoping this is the right way to go about it.

### CODE REVIEW

**Comment by sleevezipper** [comment]
Thanks a lot! I can't merge this yet as (like you said) this needs some UI stuff. I'll add that later if you're not up for it.

**Comment by department-g33k** [comment]
This is C#, right?  The closest I've come to C# is arduino code.  If it's
possible to give me a high-level idea what/where it needs to be adjusted,
I'll give it my best shot, I just don't have very much experience at all
with C#.
*Dan Brannon*
***@***.***

**Comment by sleevezipper** [comment]
Yeah it's C#. If you want to learn I'll happily help you. If you just want to have this in the application it's easier if I just do it some time soon.

**Comment by sleevezipper** [comment]
I'm closing this due to inactivity. Please create a new PR if you want to contribute.

**Pull request closed without merging**
