### PR TITLE
Microphone process sensor

### PR DESCRIPTION
**Pull request by jordandrako**
I used #128 as I template for this, and #92 had comments requesting the same for the microphone. I am not able to test if it works since I'm running into an error when running `dotnet build`:
```
C:\Program Files\dotnet\sdk\5.0.404\Microsoft.Common.CurrentVersion.targets(4999,5): error MSB3030: Could not copy the file "C:\code\hass-workstation-service\hass-workstation-service\UserInterface.pdb" because it was not found. [C:\code\hass-workstation-service\hass-workstation-service\hass-workstation-service.csproj]
```
@sleevezipper if you could point me in the right direction to get the build running so I can test this, that would be awesome.

I've cleaned up the repeated code in the Webcam Process Sensor as well as changed the sensor to report all active processes, deliminated with a comma. This may be considered a breaking change so I can remove the changes from the webcam sensor if preferred.

### CODE REVIEW

**Comment by sleevezipper** [comment]
Sorry for the shitty build instructions. I'll get back to you this weekend!

**Comment by jordandrako** [comment]
I can get the build to output the new service exe, but I don't think it's rebuilding the interface. I can manually add the new sensor to my sensors json and it works, but I don't see it in the dropdown when adding a new sensor.

**Comment by amaisano** [comment]
I think this would resolve https://github.com/sleevezipper/hass-workstation-service/issues/32 too!

**Comment by amaisano** [comment]
Waiting on the edge of my seat for this one...

**Comment by HeedfulCrayon** [comment]
> Waiting on the edge of my seat for this one...

Same here

**Comment by jordandrako** [comment]
Hey @sleevezipper, hope you had a great holiday. Just wanted to ping you to make sure this is still on your radar.

**Comment by sleevezipper** [comment]
Thanks for the heads-up! It went under my radar for a while and didn't notice the attention this received. Sorry for that! I'll make sure to spend some time on this tomorrow.

**Review by sleevezipper — APPROVED** [review]

**Comment by sleevezipper** [comment]
This is great. Thanks for your contribution! I'll get a release out as soon as I can.

**Pull request merged**
