### PR TITLE
Add master volume sensor.

### PR DESCRIPTION
**Pull request by SecretiveShell**
Because #90 has gone stale, I converted the code into a new sensor and update GUI and documentation to reflect this.

### CODE REVIEW

**Comment by sleevezipper** [comment]
Hi! Thanks for creating a new PR. The sensor should also be configurable through the UI. Would you mind adding that?

**Comment by SecretiveShell** [comment]
After making a new directory and cloning my develop branch, I have failed to replicate this issue. Here is the list of commands I used to recreate the test build :

```bash
git clone --branch develop https://github.com/SecretiveShell/hass-workstation-service
cd .\hass-workstation-service\
mkdir build
dotnet build
dotnet publish --output .\build\
cd .\build
explorer .
```
After closing the installed version of HWS using task manager I was able to initialize the new one and successfully configure the comman
[build log.txt](https://github.com/sleevezipper/hass-workstation-service/files/7492965/build.log.txt)
d

**Comment by mark007** [comment]
This is a great addition. When will there be an official release/build for those of us who do not have the dotnet build tools.

**Comment by mark007** [comment]
Were you also planning to add a SetVolumeComand from your end @SecretiveShell or is it something you would consider? My goal is to update some HA automations when I click certain "Activities" on a harmony remote, so for "Play Games" I wanted to set TV HDMI inputs (done), set wireless speaker inputs to say Optical (done), as well as set the wireless speaker volume (done) and set an appropriate windows master volume (to do).

**Comment by SecretiveShell** [comment]
That would be a nice addition, although I currently have no plans to implement this. It would require a rework of how the app handles MQTT messages.

**Pull request merged**
